#!/bin/bash

case $BLOCK_BUTTON in
    #1) termite --class ncpamixer -e ncpamixer & disown ;;
    1) pavucontrol ;;
	3) pamixer -t ;;
	4) pamixer --allow-boost -i 5 ;;
	5) pamixer --allow-boost -d 5 ;;
esac

printpastatus() { [[ $(pamixer --get-mute) = "true" ]] && echo -n 🔇 && exit
echo 🔊  $(pamixer --get-volume)% ;}
printpastatus
