#!/bin/bash

case $BLOCK_BUTTON in
    1)  #date '+%Y-%m-%d |  %H:%M:%S'
        #pkill -RTMIN+5 i3blocks
        yad --calendar --splash
        #:w
        sleep 5 ;;
esac

date '+%Y-%m-%d | %H:%M:%S'


