#!/bin/sh
acpi | cut -d " " -f3-5 |  sed -e "s/,//g;s/Discharging/🔋/;s/Charging/⚡/;s/Unknown/⚡/;s/Full/🔌/;s/ 0*/ /g;s/ :/ /g"
#acpi | cut -d " " -f3-5 |  sed -e "s/,//g;s/Discharging/🔋/;s/Unknown/🔌/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g"
