#!/bin/bash 

# UPTIME=$(uptime -p | sed "s/ hour/H/" | sed "s/ minutes/M/" | sed "s/up //" | sed "s/, /:/")
UPTIME=$(uptime -p | sed "s/ week/w/" | sed "s/ days/d/" | sed "s/ hours/h/" | sed "s/ minutes/m/" | sed "s/up //")
echo -e "$UPTIME"

